### ISSUE TITLE
Core hooks as submodule

### ISSUE THREAD

**Issue by pdenooijer** [pdenooijer/hook_event_dispatcher#105]
Will be adding them to the new `core_event_dispatcher` submodule.

**Comment by Ambient-Impact** [comment]
This is a bit of a dumb question that I'm sure I've solved before but can't remember the solution to: I just rebased on the latest, and even with ```core_event_dispatcher``` enabled and all my namespaces/dependencies updated in my own modules, the events in ```core_event_dispatcher``` and even the procedural hooks in it don't seem to be run. I did get a fatal error when enabling the module, due to not having updated the code yet - could my local Drupal install somehow be stuck thinking the module is enabled but not picking up the hooks, event after multiple cache rebuilds?

**Comment by pdenooijer** [comment]
Your 100% sure it is enabled in the database? Disable & enable it? Could be I made a typo so that's why the hooks are not getting picked up?

**Comment by Ambient-Impact** [comment]
I think I figured it out: it's that you changed the namespace paths for a bunch of those events - I only did a search and replace for ```use Drupal\hook_event_dispatcher\Event\```, but didn't look at the paths. I'm just updating them now. 😛 

Edit: indeed it was the paths. My bad. 🤦‍♀

**Comment by pdenooijer** [comment]
Ah yeah, I took that opportunity to rename some namespaces to make them reflect the right API defined in Drupal. So `Entity` events are those in the `entity.api.php`.

**Comment by Ambient-Impact** [comment]
[![I see](https://media1.tenor.com/images/e875c36a433d9ea5a52cbc59bdb5a591/tenor.gif?itemid=11903374)](https://tenor.com/view/meerkat-googly-eyes-funny-silly-gif-11903374)
