### ISSUE TITLE
Split up more events into submodules

### ISSUE THREAD

**Issue by pdenooijer** [pdenooijer/hook_event_dispatcher#97]
Split up more event into submodules so a developer has the ability to only enable the events that are needed, instead of everything. Reducing the amount of useless events send out on smaller projects.

TODO:
1. Identify what events should be grouped
1. Make PR to move them to a sub module

**Comment by Ambient-Impact** [comment]
The most straightforward way to me would be to have a module for core stuff (including the ```system``` module, etc.), and then break up the optional core module events into their own modules. For example, a ```views_event_dispatcher``` for Views events. Not sure if it's worth doing that for modules that only have one event, like the Toolbar event, but that's up to you.

**Comment by pdenooijer** [comment]
Yeah, I was thinking on long the same line. I guess the core stuff can stay in the main module or should there be an `core_event_dispatcher`? Then we could move the rest into submodules, with the right dependencies on the module that needs to be enabled (like for instance `drupal:views`).

**Comment by Ambient-Impact** [comment]
I can definitely see an argument for putting the core events in a ```core_event_dispatcher``` module, because then ```hook_event_dispatcher``` itself has a more narrow focus on providing the framework and nothing else. That said, I'm not sure how much value you'd get out of putting them in another module, since I suspect most people will use at least one of the core events.

**Comment by pdenooijer** [comment]
I do like the idea of having a slim framework kind of module. Would make it more extendible for others as well.

**Comment by Ambient-Impact** [comment]
Having slept on it (which, by the way, is uncomfortable because code is all pointy and bumpy), I think I agree. The core stuff could even be split into several modules for various groups of things, like one for entity events, others for forms, fields, and so on.

**Comment by pdenooijer** [comment]
There are some events left to be moved for path, views, user and toolbar (breakpoint?).

**Comment by Ambient-Impact** [comment]
Path, user, and views would make sense as their own modules (i.e. ```path_event_dispatcher```, ```user_event_dispatcher```, and ```views_event_dispatcher```), but at the moment there's only one toolbar event, and [```toolbar.api.php```](https://api.drupal.org/api/drupal/core%21modules%21toolbar%21toolbar.api.php/8.8.x) only defines one other hook (for a total of two hooks), so I'm curious whether you think it's worth creating a ```toolbar_event_dispatcher``` module? I'm leaning towards yes, since the toolbar is its own core module.

**Comment by pdenooijer** [comment]
Working on `path_event_dispatcher` 👍

**Comment by Ambient-Impact** [comment]
🎉🎉

I'm occupied for a while with a project, but I'll lend a hand later on when I can.

**Comment by pdenooijer** [comment]
PR for `path_event_dispatcher` is merged. Also assuming at least PHP 7.2 now, so we can use those those features as well.

**Comment by pdenooijer** [comment]
views_event_dispatcher ✅ 
toolbar_event_dispatcher ✅ 
user_event_dispatcher ✅

**Comment by pdenooijer** [comment]
toolbar_event_dispatcher ✅

**Comment by Ambient-Impact** [comment]
🎉🎉🎉🚀
